// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moeboraoauitmmxgebeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZWJvcmFvYXVpdG1teGdlYmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjE1OTEsImV4cCI6MjA3NDUzNzU5MX0.KF9ccYV4bYtH17pPic2yKj4ypGolEsOJDfqS4oLZ0g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});